---
title: "Reading and saving of the vocabulary files"
date: "`r Sys.Date()`"
output:
  github_document:
    toc: true
    toc_depth: 2
    fig_width: 7
    fig_height: 5
    df_print: tibble
editor_options: 
  chunk_output_type: console
description: >
  This code converts the .xlsx vocabulary files into .csv files for easier use in Excel Power Query and for version control.
---



```{r}
base::remove(list=ls())
```

Set-up and packages

```{r}
library(lanuprodatascience)
check_renv_r_version_match() # 🛑 Stops if R version is incompatible

#renv::activate()

# Install 'pak' if not yet installed
if (!requireNamespace("pak", quietly = TRUE)) {
  install.packages("pak")
}

# Install 'lanuprodatascience' if not yet installed
if (!requireNamespace("lanuprodatascience", quietly = TRUE)) {
  pak::pkg_install("lanupro-analytics/lanuprodatascience")
}

# Restore exact package versions (no updates)
renv::restore(prompt = FALSE, repos = NULL)
```


# Packages

```{r}
options("install.lock"=FALSE)

#If we are working in our project, we can simply use the following to load our packages
library("here")
library("readxl")
library("writexl")
```

Make a snaphot of all packages
```{r}
renv::snapshot()
```

# Read the vocabulary data

Directly from the server
```{r}
df_vocabulary_general <- read_excel(path = here("data/raw_results/lanupro_vocabulary_general.xlsx"))
df_vocabulary_fatty_acids <- read_excel(path = here("data/raw_results/lanupro_vocabulary_fatty_acids.xlsx"))
df_vocabulary_incubations <- read_excel(path = here("data/raw_results/lanupro_vocabulary_incubations.xlsx"))
```


# Processing
If needed


# Save the vocabulary data to .cvs
For excel power query and
For version control

```{r}
write.csv(df_vocabulary_general, file = here("data/processed/lanupro_vocabulary_general.csv"))
write.csv(df_vocabulary_fatty_acids, file = here("data/processed/lanupro_vocabulary_fatty_acids.csv"))
write.csv(df_vocabulary_incubations, file = here("data/processed/lanupro_vocabulary_incubations.csv"))
```



